version: '3'

services:
  insta:
    build: ./Insta/
    command: dotnet dockernet/Insta.dll
    ports:
      - "80:80"
    networks:
      - web_nw
    depends_on:
      - web

  web:
    build: ./pythonInstaScrapper/web
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app   # uncomment for production
    volumes:
      - .:/code
    ports:
      - "5000"
    networks:
      - web_nw
    # depends_on:
    #   - postgres
  
  nginx:
    image: nginx:latest
    build: ./pythonInstaScrapper/nginx
    ports:
      - "1234:1234"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - insta
    networks:
      - web_nw


volumes:
  dbdata:

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge