version: '3'

services:
  postgres:
    restart: always
    image: postgres:10
    env_file: .env
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_nw
  # db:
  #   image: postgres:latest
  #   volumes:
  #     - "dbdata:/var/lib/postgresql/data"
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app   # uncomment for production
    # command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000"
    networks:
      - web_nw
    depends_on:
      - postgres
    networks:
      - db_nw
      - web_nw
  
  nginx:
    image: nginx:latest
    build: ./nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - web_nw


volumes:
  dbdata:

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge