FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
COPY /bin/Release/netcoreapp2.2/publish/ dockernet/

# FROM microsoft/dotnet:sdk AS build-env
# COPY . insta/
# WORKDIR /insta
# RUN dotnet build
# RUN dotnet publish -c Release
# COPY ./insta/bin/Release/netcoreapp2.2/publish/ dockernet/


