version: '3'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app   # uncomment for production
    # command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    networks:
      - web_nw
    # depends_on:
    #   - postgres
    networks:
      - db_nw
      - web_nw
  
  # nginx:
  #   image: nginx:latest
  #   build: ./nginx
  #   ports:
  #     - "1234:1234"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - web
  #   networks:
  #     - web_nw


volumes:
  dbdata:

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge